export const ITEMS = {
  rusty_sword: {
    id: 'rusty_sword',
    name: 'Rusty Sword',
    slot: 'weapon',
    rarity: 'common',
    description: 'A worn blade, still sharp enough to cut.',
    bonusDamage: 3,
    icon: 'sword',
  },
  shadow_blade: {
    id: 'shadow_blade',
    name: 'Shadow Blade',
    slot: 'weapon',
    rarity: 'rare',
    description: 'A blade forged in darkness. Whispers in combat.',
    bonusDamage: 8,
    icon: 'sword',
  },
  flame_edge: {
    id: 'flame_edge',
    name: 'Flame Edge',
    slot: 'weapon',
    rarity: 'epic',
    description: 'Burns with an eternal flame.',
    bonusDamage: 15,
    icon: 'sword',
  },
  void_cleaver: {
    id: 'void_cleaver',
    name: 'Void Cleaver',
    slot: 'weapon',
    rarity: 'legendary',
    description: 'Cuts through reality itself.',
    bonusDamage: 22,
    icon: 'sword',
  },
  tattered_cloak: {
    id: 'tattered_cloak',
    name: 'Tattered Cloak',
    slot: 'armor',
    rarity: 'common',
    description: 'Offers minimal protection.',
    bonusDefense: 2,
    icon: 'shield',
  },
  knights_plate: {
    id: 'knights_plate',
    name: "Knight's Plate",
    slot: 'armor',
    rarity: 'rare',
    description: 'Heavy but reliable armor.',
    bonusDefense: 6,
    bonusHealth: 20,
    icon: 'shield',
  },
  shadow_mantle: {
    id: 'shadow_mantle',
    name: 'Shadow Mantle',
    slot: 'armor',
    rarity: 'epic',
    description: 'Woven from living shadows.',
    bonusDefense: 10,
    bonusSpeed: 30,
    icon: 'shield',
  },
  health_amulet: {
    id: 'health_amulet',
    name: 'Health Amulet',
    slot: 'accessory',
    rarity: 'common',
    description: 'A faintly glowing charm.',
    bonusHealth: 25,
    icon: 'gem',
  },
  mana_ring: {
    id: 'mana_ring',
    name: 'Mana Ring',
    slot: 'accessory',
    rarity: 'rare',
    description: 'Resonates with arcane energy.',
    bonusMana: 30,
    icon: 'gem',
  },
  speed_boots: {
    id: 'speed_boots',
    name: 'Speed Boots',
    slot: 'accessory',
    rarity: 'rare',
    description: 'Swift as the wind.',
    bonusSpeed: 60,
    icon: 'gem',
  },
  crit_charm: {
    id: 'crit_charm',
    name: 'Crit Charm',
    slot: 'accessory',
    rarity: 'epic',
    description: 'Fate favors the bold.',
    bonusDamage: 10,
    icon: 'gem',
  },
  cursed_blade: {
    id: 'cursed_blade',
    name: 'Cursed Blade',
    slot: 'weapon',
    rarity: 'epic',
    description: 'Power at a terrible price. Cuts deep but leaves you exposed.',
    bonusDamage: 18,
    icon: 'sword',
  },
  dragon_scale: {
    id: 'dragon_scale',
    name: 'Dragon Scale',
    slot: 'armor',
    rarity: 'legendary',
    description: 'Scales of an ancient dragon. Nearly indestructible.',
    bonusDefense: 14,
    bonusHealth: 35,
    icon: 'shield',
  },
  soul_siphon: {
    id: 'soul_siphon',
    name: 'Soul Siphon',
    slot: 'accessory',
    rarity: 'epic',
    description: 'Drains essence from the darkness itself.',
    bonusDamage: 8,
    bonusMana: 25,
    icon: 'gem',
  },
};

export const RARITY_COLORS = {
  common: '#94A3B8',
  rare: '#38BDF8',
  epic: '#9D4CDD',
  legendary: '#FBBF24',
};

export function getItemById(id) {
  return ITEMS[id] ? { ...ITEMS[id] } : null;
}
